version: "3.8"

services:
  mcp-http-server:
    build:
      context: .
      dockerfile: Dockerfile.github
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    env_file:
      - .env
    environment:
      # GitHub MCP Server specific environment variables
      - GITHUB_PERSONAL_ACCESS_TOKEN=${GITHUB_PERSONAL_ACCESS_TOKEN}
      - GITHUB_TOOLSETS=${GITHUB_TOOLSETS:-}
      - GITHUB_READ_ONLY=${GITHUB_READ_ONLY:-false}
      - GITHUB_DYNAMIC_TOOLSETS=${GITHUB_DYNAMIC_TOOLSETS:-false}
      - GITHUB_HOST=${GITHUB_HOST:-}
    volumes:
      - mcp_cache:/tmp/mcp-servers:rw
    restart: unless-stopped

volumes:
  mcp_cache:
    driver: local
